name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set image tags
        id: vars
        run: |
          echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag emqo/bugelll-dst:latest \
            --tag emqo/bugelll-dst:${{ env.TAG }}

      - name: Push Docker image
        run: |
          docker push emqo/bugelll-dst:latest
          docker push emqo/bugelll-dst:${{ env.TAG }}
